In [2]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

(2, 5)

In [4]:
#minimum value
np.min(arr, axis=1)

array([1, 6])

In [6]:
#maximum value
np.max(arr, axis=1)

array([ 5, 10])

In [7]:
#median value
np.median(arr, axis=1)

array([3., 8.])

In [12]:
np.argmax(arr, axis=1)

array([4, 4], dtype=int64)